# Generated by Django 2.2.26 on 2022-03-14 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='REview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('rating', models.FloatField()),
                ('description', models.CharField(max_length=256)),
                ('revieweer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review_revieweer', to=settings.AUTH_USER_MODEL)),
                ('seller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review_seller', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
